# Stage 1: Build Angular SSR
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build:ssr

# Stage 2: Runtime Node SSR
FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/dist/frontend /app/dist/frontend
COPY package*.json ./
RUN npm ci

# Novo entrypoint
COPY server.js ./

EXPOSE 4000
CMD ["node", "server.js"]
