# 1️⃣ Build Angular SSR
FROM node:22 AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build --prod

# 2️⃣ Runtime container (SSR)
FROM node:22-alpine

WORKDIR /app

# Copy results from build SSR
COPY --from=build /app/dist/frontend /app/dist/frontend
COPY package*.json ./

EXPOSE 4000
CMD ["node", "dist/frontend/server/main.js"]
